### ISSUE TITLE
trying to reproduce I get logging error for snakemake

### ISSUE THREAD

**Issue by pascalwhoop** [TranslatorSRI/Babel#457]
```
docker run --rm --mount type=bind,source=$PWD/sources,target=$PWD/babel_downloads babel
```

I get 
```
(Babel) (base) pascal_everycure_org@pascal-dev-workbench:~/code/Babel$ docker run --rm --mount type=bind,source=$PWD/sources,target=$PWD/babel_downloads babel
ERROR:snakemake.logging:ImportError in file "/code/babel/src/snakefiles/leftover_umls.snakefile", line 1:
cannot import name 'Logger' from 'snakemake.logging' (/code/babel/venv/lib/python3.12/site-packages/snakemake/logging.py)
  File "/code/babel/src/snakefiles/leftover_umls.snakefile", line 1, in <module>
  File "/code/babel/src/createcompendia/leftover_umls.py", line 6, in <module>
```

I think the dockerfile should install `requirements.lock` to be reproducible. 

which I understand doesn't work because it has locked dependencies that don't work with python 3.12. 

I'd recommend switching to uv and then resolving the dependencies once and installing via `uv.lock` in container. Much nicer experience than pip anyways

**Comment by gaurav** [comment]
I'm going to close this ticket for now, but if it's still around (or if it recurs), please reopen it!
